version: '3.3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: imdb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./:/db_files
